version: '2'

volumes:
  db-vol:

services:

  app:
    image: tcg
    build:
      context: tcg
      dockerfile: .docker/dev/Dockerfile
    container_name: tcg
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: mysql:8.0.22
    restart: always
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: tcg_db
      MYSQL_USER: tcg_user
      MYSQL_PASSWORD: tcg_pass